# Generated by Django 5.2.4 on 2025-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='bookings_bo_client__ca5b55_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['date_time'], name='bookings_fi_date_ti_98d1b8_idx'),
        ),
    ]
